/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package manajementugas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class editTugas extends javax.swing.JFrame {
    
    
    /**
     * Creates new form main
     */
    private final JDateChooser dateChooser1; // Deklarasi variabel

    public editTugas() {
        initComponents();
        dateChooser1 = new JDateChooser(); // Inisialisasi variabel
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_JudulTugas = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txt_DeskripsiTugas = new javax.swing.JTextField();
        txt_Date = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        popUpDateChooser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_JudulTugas.setBackground(new java.awt.Color(36, 36, 36));
        txt_JudulTugas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_JudulTugas.setForeground(new java.awt.Color(252, 158, 0));
        txt_JudulTugas.setBorder(null);
        txt_JudulTugas.setOpaque(true);
        txt_JudulTugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_JudulTugasActionPerformed(evt);
            }
        });
        jPanel1.add(txt_JudulTugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 850, 40));

        jPanel2.setBackground(new java.awt.Color(36, 36, 36));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 860, 40));

        jPanel3.setBackground(new java.awt.Color(36, 36, 36));

        txt_DeskripsiTugas.setBackground(new java.awt.Color(36, 36, 36));
        txt_DeskripsiTugas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_DeskripsiTugas.setForeground(new java.awt.Color(252, 158, 0));
        txt_DeskripsiTugas.setBorder(null);
        txt_DeskripsiTugas.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_DeskripsiTugas.setOpaque(true);
        txt_DeskripsiTugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DeskripsiTugasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(txt_DeskripsiTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_DeskripsiTugas, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 860, 40));

        txt_Date.setBackground(new java.awt.Color(36, 36, 36));
        txt_Date.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Date.setForeground(new java.awt.Color(252, 158, 0));
        txt_Date.setBorder(null);
        txt_Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DateActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 800, 40));

        jPanel5.setBackground(new java.awt.Color(36, 36, 36));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 810, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 158, 0));
        jLabel1.setText("Deadline");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Back_4.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 25, 23, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(252, 158, 0));
        jLabel3.setText("Edit Tugas");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, -1, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(252, 158, 0));
        jLabel4.setText("Judul");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(252, 158, 0));
        jLabel5.setText("Deskripsi Tugas");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Check Mark_2.png"))); // NOI18N
        jLabel6.setToolTipText("");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 370, 67, 64));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(252, 158, 0));
        jLabel7.setText("Prioritas");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, 30));

        jComboBox1.setBackground(new java.awt.Color(36, 36, 36));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(252, 158, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rendah", "Tinggi" }));
        jComboBox1.setBorder(null);
        jComboBox1.setOpaque(true);
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 695, -1));

        popUpDateChooser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        popUpDateChooser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Calendar.png"))); // NOI18N
        popUpDateChooser.setToolTipText("");
        popUpDateChooser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        popUpDateChooser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                popUpDateChooserMouseClicked(evt);
            }
        });
        jPanel1.add(popUpDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(856, 310, 30, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 470));
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        setSize(new java.awt.Dimension(930, 472));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DateActionPerformed

    private void txt_JudulTugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_JudulTugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_JudulTugasActionPerformed

    private void popUpDateChooserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popUpDateChooserMouseClicked
        dateChooser1.showPopup();
    }//GEN-LAST:event_popUpDateChooserMouseClicked

    private void txt_DeskripsiTugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DeskripsiTugasActionPerformed
       
    }//GEN-LAST:event_txt_DeskripsiTugasActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose(); // Menutup form login
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new main().setVisible(true); // Membuka Main
                    }
                });
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        String judulTugas = txt_JudulTugas.getText();
        String deskripsiTugas = txt_DeskripsiTugas.getText();
        String deadline = txt_Date.getText();
        String prioritasTugas = jComboBox1.getSelectedItem().toString();

        if (judulTugas.isEmpty() || deskripsiTugas.isEmpty() || deadline.isEmpty() || "Pilih".equals(prioritasTugas)) {
            JOptionPane.showMessageDialog(this, "Harap isi semua field dengan benar!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Connection con;
        PreparedStatement pst;

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/manajemen_tugas", "root", "");
            pst = con.prepareStatement("UPDATE tugas (judul, deskripsi, deadline, prioritas) VALUES (?, ?, ?, ?)");
            pst.setString(1, judulTugas);
            pst.setString(2, deskripsiTugas);
            pst.setString(3, deadline);
            pst.setString(4, prioritasTugas);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Tugas berhasil ditambahkan!");
            txt_JudulTugas.setText("");
            txt_DeskripsiTugas.setText("");
            txt_Date.setText("");
            jComboBox1.setSelectedIndex(0);
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menambahkan tugas: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
           
        this.dispose(); // Menutup form login
                java.awt.EventQueue.invokeLater(() -> {
                    new main().setVisible(true); // Membuka Main
        });
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editTugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editTugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editTugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editTugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new editTugas().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel popUpDateChooser;
    private javax.swing.JTextField txt_Date;
    private javax.swing.JTextField txt_DeskripsiTugas;
    private javax.swing.JTextField txt_JudulTugas;
    // End of variables declaration//GEN-END:variables

    private static class dateChooser1 {

        private static void showPopup() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public dateChooser1() {
        }
    }

    private static class JDateChooser {

        public JDateChooser() {
        }

        private void showPopup() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }
}
